import os 
from time import sleep

print ("Welcome to tty1 fixer \n")
sleep (0.7)
os.system ("clear")
print ("<Step 1> \n")
print (" The proggram will download some packs \n")
sleep (1.2)
os.system ("clear")
print ("Downloading sddm <display manager> \n")
print ("If a popup window comes up <select sddm > <NOT! lightsddm> \n")
nothing = input ("Press [Enter] to continue")
os.system ("clear")
print ("Please put your password")
os.system ("clear")
os.system ( "sudo apt install sddm")
os.system ("clear")
print ("Done !")
sleep (1.2)
os.system ("clear")
print ("<Step 2> \n")
print ("Select a wm \n")
print ("<Xfce4> <KDE plasma> <GNOME>")
select_wm = input ("~> ")

if select_wm == ("Xfce4") or ("Xfce"):
    os.system ("clear")
    print ("Sure")
    os.system ("sudo apt install kali-defaults kali-root-login desktop-base xfce4 xfce4-places-plugin xfce4-goodies kali-desktop-xfce")
    os.system ("clear")
    print ("Done")
    sleep (1.2)
    print ("<Step 3> \n")
    print ("Reconfigure files \n")
    os.system ("sudo dpkg-reconfigure lightdm")
    print ("Done !")
    sleep (1.2)
    os.system ("clear")
    print ("<Step finall> \n")
    print ("The system will restart in 5.2 sec \n")
    print ("Goodbye")
    sleep (5.2)
    os.system("sudo init 6")

elif select_wm == ("KDE plasma") or ("KDE"):
    os.system ("clear")
    print ("Sure")
    os.system ("sudo apt install kali-desktop-kde")
    os.system ("clear")
    print ("Done")
    sleep (1.2)
    print ("<Step 3> \n")
    print ("Reconfigure files \n")
    os.system ("sudo dpkg-reconfigure lightdm")
    print ("Done !")
    sleep (1.2)
    os.system ("clear")
    print ("<Step finall> \n")
    print ("The system will restart in 5.2 sec \n")
    print ("Goodbye")
    sleep (5.2)
    os.system("sudo init 6")

elif select_wm == ("GNOME") or ("gnome"):
    os.system ("clear")
    print ("Sure")
    os.system ("sudo apt install kali-desktop-gnome")
    os.system ("clear")
    print ("Done")
    sleep (1.2)
    print ("<Step 3> \n")
    print ("Reconfigure files \n")
    os.system ("sudo dpkg-reconfigure lightdm")
    print ("Done !")
    sleep (1.2)
    os.system ("clear")
    print ("<Step finall> \n")
    print ("The system will restart in 5.2 sec \n")
    print ("Goodbye")
    sleep (5.2)
    os.system("sudo init 6")
else:
    print ("something went wrong \n")
    print ("the proggram will restart ")
    os.system ("/bin/python /home/fert2711/Documents/m.p.o.v/tty1-fix.py")
    exit()